### ISSUE TITLE
[Bug] Console Background Display

### ISSUE THREAD

**Issue by xCykrix** [FendiTony777/SystemInfoPRO#2] opened 2019-10-08 00:11 UTC
**Describe the bug**
The console displays text in an unreadable fashion.

**To Reproduce**
1. Install the plugin and run a server with a bash terminal.

**Info Version**
Server JAR Version: 1.14.4 Paper (Build 209)
System Info PRO version: 1.2.0

**Screenshots**
![image](https://user-images.githubusercontent.com/12182390/66357860-3056a000-e936-11e9-962d-2e8489b8da4f.png)

**Comment by FendiTony777** [comment] 2019-10-08 12:34
Ok i am sorry. Although this is not a bug but just a bad choose I made. I will make it to be more readable color next update

**Comment by FendiTony777** [comment] 2019-10-10 20:22
Fixed on latest commit 1.3.0.

**Closed by FendiTony777** 2019-10-10 20:22 UTC
Labels: bug

**Comment by xCykrix** [comment] 2019-10-11 10:32
Thank you much. I just couldn't think of a better way to label this instead
of a bug.
